#!/bin/sh
TITLE="" MSG="" SOUND=""
while [ $# -gt 0 ]; do
  case "$1" in
    -title)   TITLE="$2"; shift 2;;
    -message) MSG="$2"; shift 2;;
    -sound)   SOUND="$2"; shift 2;;
    *) shift;;
  esac
done
URGENCY="normal"; [ -n "$SOUND" ] && URGENCY="critical"
printf '\033]777;notify;%s;%s\007' "$TITLE" "$MSG" > /dev/tty 2>/dev/null
exit 0
