FROM alpine

ARG TARGETARCH

# Dependencies
RUN apk add --no-cache bash tini

# Application
COPY ./dist/${TARGETARCH}/tabsh /usr/bin/tabsh

EXPOSE 7681
WORKDIR /root

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["tabsh", "-W", "bash"]
