# cmake/GenerateShims.cmake
# Usage: cmake -P cmake/GenerateShims.cmake <shims_dir> <output.h>
#
# Generates a C header from plain text files in shims/ using xxd -i.
# Each file is turned into a static const char array.

set(SHIMS_DIR "${CMAKE_ARGV3}")
set(OUTPUT  "${CMAKE_ARGV4}")

if(NOT SHIMS_DIR OR NOT OUTPUT)
  message(FATAL_ERROR "Usage: cmake -P cmake/GenerateShims.cmake <shims_dir> <output.h>")
endif()

find_program(XXD xxd)
if(NOT XXD)
  message(FATAL_ERROR "xxd not found (install vim or xxd package)")
endif()

file(WRITE "${OUTPUT}" "/* Auto-generated by cmake/GenerateShims.cmake */\n")
file(APPEND "${OUTPUT}" "#pragma once\n\n")

# ---------------------------------------------------------------------------
# Map:  relative path under shims/  →  C variable name
# ---------------------------------------------------------------------------
set(SHIM_MAP
  "notify-send"                    shim_notify_send
  "osascript"                      shim_osascript
  "terminal-notifier"              shim_terminal_notifier
  "kdialog"                        shim_kdialog
  "init/bashrc"                    init_bashrc
  "init/zshrc"                     init_zshrc
  "init/fish/config.fish"          init_fish_config
  "init/fish/conf.d/zzz-tabsh.fish" init_fish_conf
  "init/env.sh"                    init_envsh
  "init/init.ps1"                  init_pwsh
  "init/init.bat"                  init_bat
)

list(LENGTH SHIM_MAP MAP_LEN)
math(EXPR PAIRS "${MAP_LEN} / 2")
math(EXPR LAST_IDX "${PAIRS} - 1")

foreach(I RANGE 0 ${LAST_IDX})
  math(EXPR KEY_IDX "${I} * 2")
  math(EXPR VAL_IDX "${I} * 2 + 1")
  list(GET SHIM_MAP ${KEY_IDX} RELPATH)
  list(GET SHIM_MAP ${VAL_IDX} VARNAME)

  set(SRC "${SHIMS_DIR}/${RELPATH}")
  if(NOT EXISTS "${SRC}")
    message(FATAL_ERROR "Missing shim file: ${SRC}")
  endif()

  get_filename_component(SRC_DIR  "${SRC}" DIRECTORY)
  get_filename_component(SRC_FILE "${SRC}" NAME)
  execute_process(
    COMMAND "${XXD}" -i "${SRC_FILE}"
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE RAW
    RESULT_VARIABLE RES
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(NOT RES EQUAL 0)
    message(FATAL_ERROR "xxd -i failed for ${SRC}")
  endif()

  # xxd produces:
  #   unsigned char <name>[] = {
  #     0x23, ...
  #   };
  #   unsigned int <name>_len = N;
  #
  # We want to keep the hex array but rename the variable and drop the _len line.

  # 1) Extract the exact xxd-generated name from the first line
  #    First line looks like: "unsigned char shims_notify_send[] = {"
  string(FIND "${RAW}" "\n" FIRST_NL)
  string(SUBSTRING "${RAW}" 0 ${FIRST_NL} FIRST_LINE)

  string(FIND "${FIRST_LINE}" "char " CHAR_POS)
  math(EXPR NAME_START "${CHAR_POS} + 5")
  string(FIND "${FIRST_LINE}" "[]" BRACKET_POS)
  math(EXPR NAME_LEN "${BRACKET_POS} - ${NAME_START}")
  string(SUBSTRING "${FIRST_LINE}" ${NAME_START} ${NAME_LEN} XXD_NAME)
  string(STRIP "${XXD_NAME}" XXD_NAME)

  # 2) Rename declaration
  string(REPLACE "unsigned char ${XXD_NAME}[]" "static const char ${VARNAME}[]" RAW "${RAW}")

  # 3) Rename the _len variable to a static const size_t
  string(REPLACE "unsigned int ${XXD_NAME}_len = " "static const size_t ${VARNAME}_len = " RAW "${RAW}")
  # Strip trailing semicolon line's trailing junk and normalize
  string(STRIP "${RAW}" RAW)

  file(APPEND "${OUTPUT}" "${RAW}\n\n")
endforeach()

message(STATUS "Generated ${OUTPUT}")
